### ISSUE TITLE
Ensure debug variable are limited on cloud servers to avoid unapproved logging

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-devops#27]
# Introduction

When a flag `DEBUG=hopr*` is passed to HOPR nodes (e.g. bootstrap, coverbot), they can log unidentifiable minimal telemetry into our infrastructure (e.g. nodes IP and address). Although minimal, and currently only used in testnet (i.e disposable) infrastructure, this telemetry is not being described anywhere nor informed to our users neither asked for their consent. If passed to any bootstrap servers (i.e. this is currently not being the case), then HOPR Association could have records of multiple nodes IP and their respective HOPR addresses by just starting their nodes, which is a privacy and security concern, independently of the underlying protocol.

Bootstrap servers with telemetry flags enable could log information that looks something like the following:

```
hopr-core:transport:listener new inbound connection /ip4/$IP/tcp/$PORT
hopr-core:transport [$NODE] dialing /ip4/$IP/tcp/$PORT/p2p/$USER_NODE directly
```

# Task Description

- [ ] Add a Data Privacy Policy to our software to inform our users and obtain an acknowledgement from them that some telemetry could be sent to HOPR Association infrastructure (with datacenters hosted in Switzerland) on specific circumstances and provided on an opt-in basis only.
  - [ ] Create a Data Privacy Policy and publish it on our website.
  - [ ] Create a Data Privacy Policy and ship it alongside our distributions and source code.
- [ ] Provide users with a binary distribution that is explicit about the servers settings they will connect with specific telemetry.
  - [ ] Update binary distributions to show that they will ping to servers that have telemetry enabled. e.g. ship distributions like `./start-hopr-chat-telemetry.sh` and `./start-hopr-chat-private.sh`.
  - [ ] Obtain consent from the users before connecting to a bootstrap server that has telemetry enabled. e.g. prompt users with a question on start "Do you agree that by running this testing software, some minimal telemetry might be sent to $SERVER, which is currently hosted in $COUNTRY, managed by $COMPANY".
  - [ ] Provide telemetry explicit configuration options in our source code for anyone running our software.
- [ ] Update our terraform scripts and DNS records to have explicit warnings about the debug flags and to specify which nodes are running telemetry settings. e.g. `_dnsaddr.bootstrap.basodino.develop.hoprnet.org vs _dnsaddr.telemetry.bootstrap.basodino.develop.hoprnet.org`
