### ISSUE TITLE
Deploying a Ceramic node

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-devops#33]
# Background

Relevant issues and PRs:

- hoprnet/hoprnet#1431.
- https://github.com/hoprnet/hoprnet/issues/1284
- https://github.com/hoprnet/hoprnet/pull/1619

As our test nets became more popular and had more issues, it became clear we had to start logging that information somehow. [HARE](https://github.com/hoprnet/hoprnet/issues/1431) was born as a result, and we created an equivalent solution using [Ceramic](https://ceramic.network), based on the discussions seen [here](https://github.com/hoprnet/hoprnet/pull/1619). We then implemented Ceramic using an `ed25519` key, which allowed us to log the commands users would use.

Our adoption of Ceramic grew with the usage of the [HOPR Leaderboard](https://network.hoprnet.org). We wanted to provide users with the ability to link their node data w/o having to trust us with such connection and not paying/gas or broadcast this relationship to the Ethereum world making it public*. Thus, we implemented [IDX](https://idx.xyz/) as both a way to store users' data and as a small captcha for our faucet.

\* _Technically, Ceramic streams ARE publicly available for anyone to see since their [anchor](https://developers.ceramic.network/reference/javascript/anchor-service/), well, anchors these endpoints into the blockchain. However, the anchoring (AFAIK) is against the streams and not the actual data, since the actual data is on IPFS. User's data in Ceramic doesn't mean it's private, but at least is obsfucated_.

To this day, we are using Ceramic in two products:

* HOPR Leaderboard (already implemented in https://github.com/hoprnet/hopr-leaderboard/pull/127)
* HOPR Nodes (to be done in https://github.com/hoprnet/hoprnet/issues/2395)

# Introduction

With our growing usage of Ceramic, we reached their team and got into their [Early Launch Program (ELP)](https://blog.ceramic.network/ceramic-mainnet-early-launch-program/), allowing us to use Ceramic not only in the Clay network, managed by [3Box Labs](https://3boxlabs.com/). In the future, the network will be open, ensuring the network is powered by a series of parties and not only initial partners.

To join the mainnet network, we need to launch our own Ceramic node and support it within our infrastructure. This task is meant to be the epic for tracking the needed tasks to launch, support, and monitor one.

# Task Description

- [x] Agreed on the deployment strategy for Ceramic node with team
- [x] Use existing code or create it to setup the Ceramic node infrastructure automatically
- [x] Set up a reverse proxy to resolve an entry point for the Ceramic node for updates
- [x] Set up a monitoring service with alerts and log our Ceramic node status
- [x] Do some smoke tests on our Ceramic endpoint with a few write/reads and tests for completeness
- [x] Send the Ceramic team a PR to the [peerlist registry](https://github.com/ceramicnetwork/peerlist) with our node multiaddress.

# Definition of done
The epic is considered complete when Ceramic has merged a PR with our existing Ceramic node multiaddress, and is resolving write and queries against it. The code or instructions for deploying and maintaining the node are described in a repository, and there's an alert and best-effort support process for it with a few monitoring services enabled.

# Testing criteria
- [ ] A ceramic node can be spun up by executing a single execution script that @nionis, @jjperezaguinaga or @tolbrino can execute.
- [ ] Our ceramic node can be queried behind a proxy, and can be updated to another Ceramic node by @nionis , @jjperezaguinaga , @SCBuergel or @tolbrino by following some instructions.
- [ ] The ceramic node is brought down intentionally and a set of alerts were triggered and sent to @nionis , @jjperezaguinaga, @tolbrino and @SCBuergel .

# Additional notes

This is required for our [partnership announcement with Ceramic](https://www.notion.so/Ceramic-x-HOPR-Partnership-announcement-3f73daf5563340ce8612b5e6cc12fdca). The creation of this epic fixes hoprnet/org#9.

**Comment by tolbrino** [comment]
PR which added our node to the ceramic peerlist: https://github.com/ceramicnetwork/peerlist/pull/28

**Comment by tolbrino** [comment]
> Set up a reverse proxy to resolve an entry point for the Ceramic node for updates

I don't think we need an extra proxy because we own the endpoint DNS anyway and can change it anytime.

**Comment by tolbrino** [comment]
Alerting through Uptimerobot set up: see https://status.hoprnet.org/

**Comment by tolbrino** [comment]
@nionis @jjperezaguinaga Can you review the PR and go through the test criteria? Get in touch if you have questions.

**Comment by tolbrino** [comment]
@nionis Were you able to review and test the PR?

**Comment by nionis** [comment]
@tolbrino unfortunately no, will test tomorrow

**Comment by tolbrino** [comment]
The review was done, the node has been running since then and is also monitored. Closing the epic.

**Comment by jjperezaguinaga** [comment]
@tolbrino I'm not sure whether our setup is easily replicable, which is something I would like to have as a goal for anyone to use, better put, for any incoming employee in case we need to tear it up/down in the future.

I created https://github.com/ceramicnetwork/terraform-aws-ceramic/issues/7 to track this, as I believe this is something that can help across many projects and not only ourselves.
